 **Inital Imports**

In [2]:
from itertools import count 
import matplotlib.pyplot as plt 
from numpy import * 
import pandas as pd 
import numpy as np
import collections
from random import randint 
from matplotlib import style
style.use('fivethirtyeight')
%matplotlib inline 
from sklearn.metrics import mean_squared_error

**Reading the data from a URL **

In [3]:
data = pd.read_csv('../input/water_supply.csv')

In [4]:
data.tail(10)

     LANDUSE_TYPE USER  PIPE DIAM   ...    2015-10  2015-11  2015-12
2007           H2   MI        0.5   ...         17       16       13
2008           H2   MI        0.5   ...         24       24       20
2009           H2   MI        0.5   ...         18        9        3
2010           H2   MI        0.5   ...         17       17       13
2011           H2   MI        0.5   ...         30       30       30
2012           H2   MI        0.5   ...         10       10       10
2013           H2   MI        0.5   ...         18       19       13
2014           H2   MI        0.5   ...         24       24       20
2015           H2   MI        0.5   ...          7       12        9
2016           H2   MI        0.5   ...         24       24       20

[10 rows x 88 columns]

In [5]:
data.head(10)

  LANDUSE_TYPE USER  PIPE DIAM   ...    2015-10  2015-11  2015-12
0           H3   MI        0.5   ...         27       22       21
1           H3   HI        0.5   ...         27       27       24
2           H3   MI        0.5   ...         18       18       24
3           H3   HI        0.5   ...         17       17       24
4           H3   HI        0.5   ...         26       33       32
5           H3   HI        0.5   ...          7        7        4
6           H3   HI        0.5   ...          3        3       24
7           H3   MI        0.5   ...         33       27       27
8           H3   MI        0.5   ...          5        4        5
9           H3   HI        0.5   ...          1        1        1

[10 rows x 88 columns]

In [6]:
customerId = int(input('Enter the Customer ID - '))

Enter the Customer ID - 2

**Extracting the necessary fields**

In [7]:
customerData = data.iloc[customerId][4:]
customerData.head(10)

2009-01    20
2009-02    20
2009-03    20
2009-04    20
2009-05    20
2009-06    20
2009-07    20
2009-08    17
2009-09    14
2009-10    10
Name: 2, dtype: object

In [8]:
cleanedData = pd.DataFrame({'Time':customerData.index, 'Water':customerData.values})
cleanedData.head(10)

      Time Water
0  2009-01    20
1  2009-02    20
2  2009-03    20
3  2009-04    20
4  2009-05    20
5  2009-06    20
6  2009-07    20
7  2009-08    17
8  2009-09    14
9  2009-10    10

**Storing the fields required in another dataframe**

In [9]:
data = cleanedData
data.head(10)

      Time Water
0  2009-01    20
1  2009-02    20
2  2009-03    20
3  2009-04    20
4  2009-05    20
5  2009-06    20
6  2009-07    20
7  2009-08    17
8  2009-09    14
9  2009-10    10

In [10]:
data.tail(10)

       Time Water
74  2015-03    19
75  2015-04    19
76  2015-05    18
77  2015-06    18
78  2015-07    19
79  2015-08    19
80  2015-09    19
81  2015-10    18
82  2015-11    18
83  2015-12    24

**The required fields are extracted **

In [11]:
x = data['Time']
y = data['Water']

In [15]:
x.head(10)

0    2009-01
1    2009-02
2    2009-03
3    2009-04
4    2009-05
5    2009-06
6    2009-07
7    2009-08
8    2009-09
9    2009-10
Name: Time, dtype: object

In [16]:
y.head(10)

0    20
1    20
2    20
3    20
4    20
5    20
6    20
7    17
8    14
9    10
Name: Water, dtype: object

In [22]:
window_size = 10 
window = np.ones(int(window_size))/window_size
window

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [23]:
moving_average = np.convolve(y , window , 'same')
print(moving_average)

[10.0 12.0 14.0 15.7 17.099999999999998 18.099999999999998
 17.200000000000003 16.099999999999998 15.6 14.6 13.700000000000001
 13.600000000000001 13.8 15.100000000000001 15.399999999999999
 17.599999999999998 19.0 20.299999999999997 20.9 22.099999999999998 23.8
 25.900000000000002 26.300000000000004 24.400000000000006
 25.500000000000004 25.300000000000004 26.6 26.800000000000004
 28.500000000000004 28.400000000000002 27.400000000000006
 25.400000000000002 24.600000000000005 25.400000000000002 24.1
 22.900000000000002 20.800000000000004 20.099999999999998 18.0 17.5
 17.299999999999997 16.9 16.7 16.299999999999997 16.4 16.1
 15.899999999999999 15.7 14.0 13.600000000000001 13.1 17.2
 17.400000000000002 17.700000000000003 18.0 18.6 17.1 17.700000000000003
 19.700000000000003 20.800000000000004 21.599999999999998 17.4
 16.900000000000002 17.3 17.1 18.0 19.9 19.0 18.8 18.300000000000004 18.3
 18.7 19.200000000000003 18.800000000000004 19.0 17.9 17.9
 18.500000000000004 18.500000000000004 19.1 17.200000000000003
 15.300000000000002 13.500000000000002 11.700000000000001]

In [26]:
average = moving_average.tolist()
average[:10]

[10.0,
 12.0,
 14.0,
 15.7,
 17.099999999999998,
 18.099999999999998,
 17.200000000000003,
 16.099999999999998,
 15.6,
 14.6]

In [29]:
residual = y - average 
residual[:10]

0     10
1      8
2      6
3    4.3
4    2.9
5    1.9
6    2.8
7    0.9
8   -1.6
9   -4.6
Name: Water, dtype: object

In [32]:
std = np.std(residual)
std

7.127186281910425

In [34]:
sigma = 1 
testing_std = residual.rolling(window_size).std()
testing_std[:10]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9    4.33646
Name: Water, dtype: float64

In [45]:
testing_std_df = pd.DataFrame(testing_std)
testing_std_df.head(20)

       Water
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9   4.336460
10  3.917610
11  3.719633
12  3.210140
13  3.203626
14  3.073109
15  3.012954
16  3.046400
17  4.691612
18  4.792123
19  5.691173

In [49]:
testing_std_df = testing_std_df.dropna(axis=0,how='all')
testing_std_df.head(10)

       Water
9   4.336460
10  3.917610
11  3.719633
12  3.210140
13  3.203626
14  3.073109
15  3.012954
16  3.046400
17  4.691612
18  4.792123

In [53]:
testing_std_df = testing_std_df.reset_index(drop=True)
testing_std_df.head(10)

      Water
0  4.336460
1  3.917610
2  3.719633
3  3.210140
4  3.203626
5  3.073109
6  3.012954
7  3.046400
8  4.691612
9  4.792123

In [58]:
rolling_std = testing_std_df.iloc[:,0].tolist()
rolling_std[:10]

[4.336460410160444,
 3.9176098155210237,
 3.7196325983444485,
 3.210140183854905,
 3.203626417393612,
 3.0731091747609622,
 3.012953515885848,
 3.046400426003706,
 4.691611900213212,
 4.79212316666052]